### ISSUE TITLE
XCode 12.0 compile error

### ISSUE THREAD

**Issue by Shamsiddin** [AndyQ/NFCPassportReader#72]
Tools:
XCode version: 12.0 (12A7209)
Simulator: iPhone 8 (iOS 13.4)
Project language: Swift 5
MacOS version: 10.15.4

Everything was working well in a XCode 11.5
With XCode 12.0 giving an error as shown in a screenShot:

<img width="1552" alt="Screen Shot 2020-09-19 at 19 33 40" src="https://user-images.githubusercontent.com/1701234/93669642-11054400-faaf-11ea-94e8-b46c1f2fa638.png">

Looking forward to the new version of the Lib!

**Comment by AndyQ** [comment]
I've got a fix for this - I haven't yet been able to test it (as I currently don't have access to my test passport that supports Active Authentication)

If you replace lines 321-323 in the above with :
        let sigData = signature
        sigData.withUnsafeBufferPointer { (unsafeBufPtr) in
            let unsafePointer = unsafeBufPtr.baseAddress!
            BN_bin2bn(unsafePointer, 32, ecsig?.pointee.r)
            BN_bin2bn(unsafePointer + 32, 32, ecsig?.pointee.s)
        }

That will fix the compile issue and should work (but I can't confirm)

**Comment by AndyQ** [comment]
Tested an 1.0.12 pushed - please test and let me know if this resolves your issue

**Comment by Punkers** [comment]
I was having the same issue as @Shamsiddin, so I updated the library to 1.0.12.
The compilation error is gone, but now the app crashes on startup with the following error

![Schermata 2020-09-24 alle 09 56 32](https://user-images.githubusercontent.com/2233765/94117323-5c6f7780-fe4c-11ea-8689-f354200e48e4.png)

I experienced it both on your example app and on a test app, both on device and simulator.

XCode version: 12.0 (12A7209)
Simulator: iPhone 11 (iOS 14)
Device: iPhone 11 (iOS 14)
Project language: Swift 5
MacOS version: 10.15.6

**Comment by Shamsiddin** [comment]
@AndyQ sorry for late response!
It was worked perfectly. Thanks!
